# user story 10
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'android'
          android-platform: 'android-31'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew build

      - name: Check Formatting
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: |
          ./gradlew build
          ./gradlew check

  prevent-merge:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Block merge if previous jobs failed
        run: exit 1
        if: ${{ needs.build.result == 'failure' }}
