name: Android CI

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'android'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Add more steps for testing, linting, etc.

  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for CI status
        if: always()
        run: |
          if [ $(jobs=$(curl -s -X GET -G "https://api.github.com/repos/akshaygupta888/2340p2/actions/runs/${GITHUB_RUN_ID}/jobs" | jq -r '.jobs[].conclusion') && [[ "${jobs[@]}" =~ "failure" ]]) ]; then
            echo "One or more jobs failed. This branch cannot be merged."
            exit 1
          else
            echo "All jobs passed. Branch can be merged."
          fi
